version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: mysql-db
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: db-eureka
      MYSQL_USER: mysql-db-eureka
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    networks:
      - mysql-network
    
volumes:
  db-data:
networks:
  mysql-network:
    driver: bridge